name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
      with:
        node-version: "20.18"
        registry-url: 'https://registry.npmjs.org'
    - name: Latest NPM
      run: |
        npm install --loglevel verbose.
        find . -name node_modules
        ls
        pwd
        npm run build
    - name: Build the Docker image
      run: docker build packages/cli --tag my-image-name:$(date +%s)
