name: Docker Image CI

on:
  push

env:
  PRIV_REGISTRY: sandboxregistry.azurecr.io

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
      with:
        node-version: "20.18"
        registry-url: 'https://registry.npmjs.org'
    - name: Latest NPM
      run: |
        npm install
        npm run build
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.PRIV_REGISTRY }}
        username: ${{ secrets.PRIV_REGISTRY_USERNAME }}
        password: ${{ secrets.PRIV_REGISTRY_PASSWORD }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
          context: packages/cli
          push: true
          tags: |
            ${{ env.PRIV_REGISTRY }}/${{ github.repository }}/$(basename $i):${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
          labels: |
            ${{ env.PRIV_REGISTRY }}/${{ github.repository }}/$(basename $i):${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
          build-args: |
            TAG=${{ github.ref_name == 'main' && 'latest' || github.ref_name }}