name: Docker Image CI

on:
  push

env:
  PRIV_REGISTRY: sandbox.acr.io

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
      with:
        node-version: "20.18"
        registry-url: 'https://registry.npmjs.org'
    - name: Latest NPM
      run: |
        npm install
        npm run build
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.PRIV_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build the Docker image
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          TAG=${{ github.ref_name }}
        elif [[ "${{ github.ref }}" == refs/heads/main ]]; then
          TAG=latest
        else
          TAG=${{ github.ref_name }}
        fi
        docker build packages/cli --tag $PRIV_REGISTRY/${{ github.repository }}}}/$(basename $i):$TAG